### ISSUE TITLE
sh: react-scripts: command not found

### ISSUE THREAD

**Issue by elmaratlason** [hgop/week2#1]
hæ
er að fá þessa villu þegar ég keyri: npm run-script build í Jenkinsfile (sh 'npm run-script build'), ég er orðinn hálf blár í framan af gúggli, veit einhver hvað vantar? (næ að builda locally)

> client@0.1.0 build /var/lib/jenkins/workspace/hgop/client
> export NODE_PATH=./src/ && react-scripts build

sh: react-scripts: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! client@0.1.0 build: `export NODE_PATH=./src/ && react-scripts build`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the client@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /var/lib/jenkins/.npm/_logs/2017-12-06T22_18_57_728Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! an-outlandish-mean-app@1.0.0 buildclient: `cd ./client && npm run build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the an-outlandish-mean-app@1.0.0 buildclient script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above

**Comment by SenpaiPlz** [comment]
This sounds like a problem with either access or installation of the create-react-app npm package.
Have you made sure to install it such that the jenkins server can utilize it?

**Comment by elmaratlason** [comment]
npm install in the client dir, did the trick!
